const EMOJI_MAP: Record<string, string> = {
  // thumbs / hands / common reactions
  "+1": "👍",
  thumbsup: "👍",
  "-1": "👎",
  thumbsdown: "👎",
  ok_hand: "👌",
  clap: "👏",
  raised_hands: "🙌",
  pray: "🙏",
  muscle: "💪",
  handshake: "🤝",
  wave: "👋",
  point_up: "☝️",
  point_down: "👇",
  point_left: "👈",
  point_right: "👉",
  v: "✌️",
  fist: "✊",
  facepalm: "🤦",
  shrug: "🤷",
  vulcan_salute: "🖖",
  call_me_hand: "🤙",
  metal: "🤘",
  crossed_fingers: "🤞",

  // hearts
  heart: "❤️",
  orange_heart: "🧡",
  yellow_heart: "💛",
  green_heart: "💚",
  blue_heart: "💙",
  purple_heart: "💜",
  black_heart: "🖤",
  white_heart: "🤍",
  brown_heart: "🤎",
  broken_heart: "💔",
  heartpulse: "💗",
  two_hearts: "💕",
  sparkling_heart: "💖",

  // faces - smiling
  grinning: "😀",
  smiley: "😃",
  smile: "😄",
  grin: "😁",
  laughing: "😆",
  satisfied: "😆",
  sweat_smile: "😅",
  rofl: "🤣",
  joy: "😂",
  slightly_smiling_face: "🙂",
  upside_down_face: "🙃",
  wink: "😉",
  blush: "😊",
  innocent: "😇",

  // faces - love / positive
  heart_eyes: "😍",
  smiling_face_with_three_hearts: "🥰",
  kissing_heart: "😘",
  kissing: "😗",
  kissing_smiling_eyes: "😙",
  kissing_closed_eyes: "😚",
  yum: "😋",
  stuck_out_tongue: "😛",
  stuck_out_tongue_winking_eye: "😜",
  zany_face: "🤪",
  stuck_out_tongue_closed_eyes: "😝",
  money_mouth_face: "🤑",
  hugs: "🤗",
  hugging_face: "🤗",
  hand_over_mouth: "🤭",
  shushing_face: "🤫",
  thinking_face: "🤔",
  thinking: "🤔",

  // faces - neutral / sleep
  zipper_mouth_face: "🤐",
  raised_eyebrow: "🤨",
  neutral_face: "😐",
  expressionless: "😑",
  no_mouth: "😶",
  smirk: "😏",
  unamused: "😒",
  roll_eyes: "🙄",
  grimacing: "😬",
  lying_face: "🤥",
  relieved: "😌",
  pensive: "😔",
  sleepy: "😪",
  drooling_face: "🤤",
  sleeping: "😴",

  // faces - negative
  mask: "😷",
  face_with_thermometer: "🤒",
  face_with_head_bandage: "🤕",
  nauseated_face: "🤢",
  vomiting_face: "🤮",
  sneezing_face: "🤧",
  hot_face: "🥵",
  cold_face: "🥶",
  woozy_face: "🥴",
  dizzy_face: "😵",
  exploding_head: "🤯",
  cowboy_hat_face: "🤠",
  partying_face: "🥳",
  sunglasses: "😎",
  nerd_face: "🤓",
  monocle_face: "🧐",
  confused: "😕",
  worried: "😟",
  slightly_frowning_face: "🙁",
  frowning_face: "☹️",
  open_mouth: "😮",
  hushed: "😯",
  astonished: "😲",
  flushed: "😳",
  pleading_face: "🥺",
  frowning: "😦",
  anguished: "😧",
  fearful: "😨",
  cold_sweat: "😰",
  disappointed_relieved: "😥",
  cry: "😢",
  sob: "😭",
  scream: "😱",
  confounded: "😖",
  persevere: "😣",
  disappointed: "😞",
  sweat: "😓",
  weary: "😩",
  tired_face: "😫",
  yawning_face: "🥱",
  triumph: "😤",
  rage: "😡",
  angry: "😠",
  cursing_face: "🤬",
  star_struck: "🤩",

  // animals / nature
  fire: "🔥",
  star: "⭐",
  star2: "🌟",
  sparkles: "✨",
  zap: "⚡",
  boom: "💥",
  collision: "💥",
  dash: "💨",
  sweat_drops: "💦",
  droplet: "💧",
  cloud: "☁️",
  sun: "☀️",
  sunny: "☀️",
  rainbow: "🌈",
  snowflake: "❄️",

  // objects / symbols common in reactions
  tada: "🎉",
  confetti_ball: "🎊",
  trophy: "🏆",
  medal_sports: "🏅",
  first_place_medal: "🥇",
  second_place_medal: "🥈",
  third_place_medal: "🥉",
  rocket: "🚀",
  dart: "🎯",
  bulb: "💡",
  eyes: "👀",
  brain: "🧠",
  bomb: "💣",
  hourglass: "⌛",
  hourglass_flowing_sand: "⏳",
  alarm_clock: "⏰",
  watch: "⌚",
  warning: "⚠️",
  no_entry: "⛔",
  no_entry_sign: "🚫",
  bell: "🔔",
  no_bell: "🔕",
  mute: "🔇",
  speaker: "🔈",
  loud_sound: "🔊",
  mega: "📣",
  loudspeaker: "📢",
  question: "❓",
  grey_question: "❔",
  exclamation: "❗",
  heavy_exclamation_mark: "❗",
  grey_exclamation: "❕",
  bangbang: "‼️",
  interrobang: "⁉️",
  "100": "💯",
  "1234": "🔢",
  ok: "🆗",
  new: "🆕",
  up: "🆙",
  cool: "🆒",
  free: "🆓",

  // checks / x / arrows
  white_check_mark: "✅",
  "green-check-mark": "✅",
  heavy_check_mark: "✔️",
  ballot_box_with_check: "☑️",
  x: "❌",
  negative_squared_cross_mark: "❎",
  heavy_multiplication_x: "✖️",
  heavy_plus_sign: "➕",
  heavy_minus_sign: "➖",
  heavy_division_sign: "➗",
  curly_loop: "➰",
  loop: "➿",
  arrow_up: "⬆️",
  arrow_down: "⬇️",
  arrow_left: "⬅️",
  arrow_right: "➡️",
  arrow_upper_left: "↖️",
  arrow_upper_right: "↗️",
  arrow_lower_right: "↘️",
  arrow_lower_left: "↙️",
  arrow_right_hook: "↪️",
  leftwards_arrow_with_hook: "↩️",
  arrow_heading_up: "⤴️",
  arrow_heading_down: "⤵️",

  // food / drink (common in reactions)
  coffee: "☕",
  beer: "🍺",
  beers: "🍻",
  champagne: "🍾",
  wine_glass: "🍷",
  cocktail: "🍸",
  pizza: "🍕",
  hamburger: "🍔",
  taco: "🌮",
  popcorn: "🍿",
  cake: "🍰",
  birthday: "🎂",
  cookie: "🍪",
  doughnut: "🍩",

  // other common
  poop: "💩",
  hankey: "💩",
  shit: "💩",
  skull: "💀",
  ghost: "👻",
  alien: "👽",
  robot: "🤖",
  see_no_evil: "🙈",
  hear_no_evil: "🙉",
  speak_no_evil: "🙊",
  dog: "🐶",
  cat: "🐱",
  unicorn: "🦄",
  pig: "🐷",
  monkey_face: "🐵",
  bug: "🐛",
  ant: "🐜",
  honeybee: "🐝",
  bee: "🐝",
  beetle: "🐞",
  snake: "🐍",
  dragon: "🐉",
  whale: "🐳",
  dolphin: "🐬",
  octopus: "🐙",
  fish: "🐟",
  shark: "🦈",
};

export function emojify(name: string): string | null {
  const clean = name.replace(/^:|:$/g, "");
  return EMOJI_MAP[clean] ?? null;
}

export function unicodeHexToEmoji(hex: string): string {
  return hex
    .split("-")
    .map((part) => String.fromCodePoint(parseInt(part, 16)))
    .join("");
}

export function renderEmojiName(name: string, unicode?: string): string {
  if (unicode) {
    try {
      return unicodeHexToEmoji(unicode);
    } catch {
      // fall through
    }
  }
  return emojify(name) ?? `:${name}:`;
}
